version: '2'

services:
  mercury-supe:
    build: .
    container_name: mercury-supe
    image: apache2-php81
    restart: always
    ports:
      - '7000:80'
    volumes:
      - ./app:/var/www/html
    environment:
      TZ: America/Maceio
    networks:
      - mercury-network

networks:
  mercury-network:
    external: true